name: Deploiement du docker-compose contenant (prometheus, node-exporter, grafana, mariadb et wordpress)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        MARIADB_DATABASE: ${{ vars.MARIADB_DATABASE }}
        MARIADB_USER: ${{ vars.MARIADB_USER }}
        WORDPRESS_DB_PASSWORD: ${{ secrets.WORDPRESS_DB_PASSWORD }}
        MARIADB_ROOT_PASSWORD: ${{ secrets.MARIADB_ROOT_PASSWORD }}
        GF_SECURITY_ADMIN_USER: ${{ secrets.GF_SECURITY_ADMIN_USER }}
        GF_SECURITY_ADMIN_PASSWORD: ${{ secrets.GF_SECURITY_ADMIN_PASSWORD }}
    steps:
      - name: Recuperation du depot
        uses: actions/checkout@v4

      - name: Validation du Docker Compose
        run: docker compose config

      - name: Demarrage de la stack Docker Compose
        run: docker compose up -d 

      - name: Attente du demarrage des services
        run: sleep 20
      
      - name: Test de Prometheus
        run: curl -f http://localhost:9090/-/healthy

      - name: Test de Grafana
        run: curl -f http://localhost:3000/api/health

      - name: Affichage des logs en cas d'echec
        if: failure()
        run: docker compose logs

      - name: Liste des conteneurs en cours d'execution
        run: docker ps -a

      - name: Arret de la stack Docker Compose
        if: always()
        run: docker compose down
      
